# -*- coding: utf-8 -*-
"""15_17_sept_summerization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UwKtCzSKSjLQn69N7vugGzHUJH4HWQpg
"""

! pip install transformers==4.53.2 datasets==4.0.0 evaluate==0.4.5 accelerate==1.9.0

from datasets import load_dataset

billsum = load_dataset("dany0407/billsum",split="ca_test")

billsum

billsum[0]

billsum = billsum.train_test_split(test_size=0.2)

billsum

billsum["train"][0]

from transformers import AutoTokenizer

checkpoint = "google-t5/t5-small"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

prefix = "summarize: "


def preprocess_function(examples):
    inputs = [prefix + doc for doc in examples["text"]]
    model_inputs = tokenizer(inputs, max_length=1024, truncation=True)

    labels = tokenizer(text_target=examples["summary"], max_length=128, truncation=True)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_billsum = billsum.map(preprocess_function, batched=True)

tokenized_billsum

tokenized_billsum["train"][0]

from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=checkpoint)

!pip install rouge_score

import evaluate
rouge = evaluate.load("rouge")

tokenizer.pad_token_id

import numpy as np


def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)

    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in predictions]
    result["gen_len"] = np.mean(prediction_lens)

    return {k: round(v, 4) for k, v in result.items()}

from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer

model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)

training_args = Seq2SeqTrainingArguments(
    output_dir="summarization_model",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    weight_decay=0.01,
    save_total_limit=3,
    num_train_epochs=10,
    predict_with_generate=True,
    fp16=True, #change to bf16=True for XPU
    push_to_hub=True,
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_billsum["train"],
    eval_dataset=tokenized_billsum["test"],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()

text = "summarize: The Inflation Reduction Act lowers prescription drug costs, health care costs, and energy costs. It's the most aggressive action on tackling the climate crisis in American history, which will lift up American workers and create good-paying, union jobs across the country. It'll lower the deficit and ask the ultra-wealthy and corporations to pay their fair share. And no one making under $400,000 per year will pay a penny more in taxes."

text

trainer.push_to_hub()

from transformers import pipeline

summarizer = pipeline("summarization", model="rushikeshwalode/summarization_model")
summarizer(text)

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("rushikeshwalode/summarization_model")
inputs = tokenizer(text, return_tensors="pt").input_ids

inputs

from transformers import AutoModelForSeq2SeqLM

model = AutoModelForSeq2SeqLM.from_pretrained("rushikeshwalode/summarization_model")
outputs = model.generate(inputs, max_new_tokens=100, do_sample=False)

outputs

tokenizer.decode(outputs[0], skip_special_tokens=True)

